safe: false
source: .
destination: ./_site

lsi: false
pygments: true

paginate: 5

motto: "cat /dev/random > /dev/null"

contacts:
   - title: "Linkedin"
     fragment: "linkedin.html"

   - title: "Coderbits"
     img: "images/coderbits.png"
     url: "https://coderbits.com/fableal"

   - title: "Twitter"
     fragment: "twitter.html"

   - title: "Github"
     img: "images/github.png"
     url: "http://www.github.com/fabriceleal"

