safe: false
source: .
destination: ./_site

lsi: false
pygments: true

paginate: 5

motto: "cat /dev/random > /dev/null"

contacts:
   - title: "Email"
     fragment: "email.html"

   - title: "Linkedin"
     fragment: "linkedin.html"

   - title: "Coderbits"
     fragment: "coderbits.html"

   - title: "Twitter"
     fragment: "twitter.html"

   - title: "Github"
     fragment: "github.html"

additional_configs:
   - _projects.yml
